name: epub_kitty_example
description: Demonstrates how to use the epub_kitty plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  permission_handler: ^4.2.0+hotfix.1
  dio: ^3.0.9
  path_provider: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  hive_generator: ^0.5.0

  epub_viewer:
    path: ../


flutter:
  uses-material-design: true
  assets:
    - assets/
