name: epub_reader
description: Epub reader using epub_kitty plugin to encapsulate FolioReaderKit
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  permission_handler: ^4.2.0+hotfix.1
  dio: ^3.0.9
  path_provider: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  hive_generator: ^0.5.0

  epub_viewer:
    path: ../


flutter:
  uses-material-design: true

  assets:
    - assets/